# -*- coding: utf-8 -*-
"""

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fmQNoCHEe0AoGbXu4S37gfaYKjVPwwNJ
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.optimizers import RMSprop

# Get dataset
X_pos, X_neg = [], []
for f in os.listdir('.'):
    if "jpeg" in f:
        X_pos.append(plt.imread(f))
X_pos = np.array(X_pos)
y_pos = np.ones((X_pos.shape[0], 1))
for f in os.listdir('sample_data'):
    if "jpeg" in f:
        X_neg.append(plt.imread('sample_data/' + f))
X_neg = np.array(X_neg)
# Undersample to correct class imbalance: 2.87% of images contain a pool.
np.random.shuffle(X_neg)
X_neg = X_neg[:X_pos.shape[0]]
y_neg = np.zeros((X_neg.shape[0], 1))

X = np.concatenate((X_pos, X_neg)) / 255
y = np.concatenate((y_pos, y_neg))

# Shuffle data to mix pos and neg
i = np.random.permutation(X.shape[0])
i_split = int(np.floor(0.8 * X.shape[0]))
X_train, X_test = X[i[:i_split]], X[i[i_split:]]
y_train, y_test = y[i[:i_split]], y[i[i_split:]]

model = Sequential()
model.add(Conv2D(64, (3, 3), padding='same', activation='relu',
                 input_shape=(256, 256, 3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(128, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(128, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer=RMSprop(lr=0.0001),
              metrics=['binary_accuracy'])
model.fit(X_train, y_train, epochs=20, batch_size=32,
          validation_data=(X_test, y_test),
          class_weight={0: 0.9, 1: 0.1})

model.save('model.h5')

for x in X_test[(((model.predict(X_test) > 0.5) * 1) != y_test).flatten()]:
    plt.imshow(x)
    plt.show()

